version: "3.8"
services:
  recorddb:
    image: mongo
    container_name: recorddb
    ports:
      - "27017:27017"
    volumes:
      - /Users/lime/mediscreen-record:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mediscreen-record:
    image: mediscreen-record
    container_name: mediscreen-record
    restart: always
    build:
      context: "./"
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      MONGO_HOST: recorddb
      MONGO_PORT: 27017
    depends_on:
      - recorddb